Iter1
mikesvis/gmart pull request #1
Opened 2024-08-24 16:04 UTC by mikesvis

2024-08-29 18:38 UTC, capsulated requested changes
Всё в комментах

Остальное обсудили на 1-1. По доработкам в основном мелочи, немного порядок навести. Всё написано хорошо, читаемо, распределено по пакетам.

Но кроме мелких замечаний есть только одно серьёзное: нужны тесты, хотя бы на основную логику

2024-08-29 18:38 UTC, capsulated commented on cmd/gophermart/main.go
> +	app := app.New(&ctx)
В конструктор контекст не передаётся:, только в методы. Да и зачем он здесь, с ним всё равно ничего не происходит. Актуально, скорее всего, создавать его уже внутри `app`

2024-08-29 18:38 UTC, capsulated commented on cmd/gophermart/main.go
> +	app := app.New(&ctx)
Да и в принципе, в приложении, где только один экземпляр app, то и сам этот слой, в прицнипе, и не нежуе. Если в метриках два приложения (и в итоге два бинарника) - то в таком случае дополнительный слой app может быть актуальным (хотя всё в двух разных пакетах `cmd` может быть - тоже как вариант), расскажу об этом на 1-1

2024-08-29 18:38 UTC, capsulated commented on internal/app/app.go
> +	config := config.NewConfig()
конфиг, кстати, можно парсить на уровне cmd, и готовый конфиг уже передавать в параметр конструктора приложухи

2024-08-29 18:38 UTC, capsulated commented on internal/app/app.go
> +	db, _ := driversDb.NewPostgres(config)
ОБЯЗАТЕЛЬНО обрабатывать и ошибки, ОСОБЕННО при инициализации ))

2024-08-29 18:38 UTC, capsulated commented on internal/app/app.go
> +	if err := http.ListenAndServe(string(app.config.RunAddress), app.router); err != nil {
Можно уже свой экземпляр сервера создать:
```go
srv := &http.Server{ /* с кастомными настройками */ }
```

2024-08-29 18:38 UTC, capsulated commented on internal/context/user.go
> +const UserIDContextKey ContextKey = "UserID"
Я не советую контекст использовать для `userID`, хотя это считается нормальная практика. Лучше никакие '**_внутрисервисные_**' данные в контекст не передавать, а '**_межсервисные_**' (id трассировки или другие подобные идентификаторы)

2024-08-29 18:38 UTC, capsulated commented on internal/domain/status.go
> +package domain
Если используется DDD, тогда обязательно надо описать применяемый подход в README.md

Лично я сторонник классического подхода сообщества go. Пример - стандартная библиотека go, можно посмотреть исходники, там нет domain, usecase и service entity и тп. Всегда имена собственные без обобщённых пакетов из подходов (это уже почти фреймворк, что не `go way`)

2024-08-29 18:38 UTC, capsulated commented on internal/domain/user.go
На мой взгляд удобнее не модели делать общими, а доп сервисные слои, внутри которых эти модели. И передавать скорее воркер (сервис) оперирующий этими моделями. Это по возможности. Когда по-другому никак не сделать, тогда можно создать независимый пакет с необходимой моделью, и возможно, несколькими методами конвертации или (иногда) даже конструкторами

2024-08-29 18:38 UTC, capsulated commented on internal/drivers/postgres/postgres.go
> +package drivers
а package точно `drivers`? разве не `postgres`? Папки тогда не требуются, немного сбивает с толку (получается пакетов `queue` и `postgres` вообще не существует

2024-08-29 18:38 UTC, capsulated commented on internal/drivers/queue/queue.go
> +type Queue struct {
`Queue` как-то не похоже на драйвер. А я обрадовался, подумал тут Rabbit или Kafka =)))

2024-08-29 18:38 UTC, capsulated commented on internal/exchange/accrual/accrual.go
> +type OrderAccrualResponse struct {
А точно экспортируемый тип должен быть?

2024-08-29 18:38 UTC, capsulated commented on internal/exchange/accrual/accrual.go
> +type Exchange struct {
Не совсем понятно, что это за сущность. Хорошо бы как-то уточнить неминг

2024-08-29 18:38 UTC, capsulated commented on internal/exchange/accrual/accrual.go
> +func NewExchange(config *config.Config, logger *zap.SugaredLogger) *Exchange {
если обычно конструктор даже не описываю, когда внутри функции-конструктора нет никакой инициализации, а сразу использую создание указателя на экземпляр `accexchange := &accrucal.Exchange{config, logger}` без функции New....

2024-08-29 18:38 UTC, capsulated commented on internal/exchange/accrual/accrual.go
> +type Exchange struct {
А, это клиент, который к accrual обращается, правильно?

2024-08-29 18:38 UTC, capsulated commented on internal/handler/handler.go
> +type Handler struct {
`Handler`, `Server` и `Router` можно, в принципе, в одном пакете описать, в разных файлах, а пакет назвать, к примеру `api` или `server`. Это комментарий уровня info)

2024-08-29 18:38 UTC, capsulated commented on cmd/gophermart/main.go
> +	app.Run()
// todo graceful shutdown

2024-08-29 18:38 UTC, capsulated commented on internal/app/app.go
> +	go accrualService.RunQueue(*ctx)
Перенести в ран

2024-08-29 18:38 UTC, capsulated commented on internal/handler/handler.go
> +func NewHandler(config *config.Config, user *user.Service, order *order.Service, accrual *accrual.Service, logger *zap.SugaredLogger) *Handler {
Я обычно не создаю конструкторы, если доп инициализации нет

2024-08-29 18:38 UTC, capsulated commented on internal/handler/userbalance.go
> +	// У меня есть вопросы!!! Передайте пожалуста товарщиу кто составлял задание
Слууушай, можно написать да, круатору, сказать что есть замечание к авторам по этому поводу. Обязательно возьмут в работу эту историю

2024-08-29 18:38 UTC, capsulated commented on internal/handler/userbalance.go
> +	// Я тогда тоже буду выкручиваться: просто у себя создавать такой заказ (который указан в списании)
Всё верно, ориентируемся именно на автотест для реализации задания. Такое, так сказать, ТЗ в договоре)))

2024-08-29 18:38 UTC, capsulated commented on internal/handler/userbalance.go
> +	"github.com/mikesvis/gmart/internal/context"
Это какой-то особенный контекст?

2024-08-29 18:38 UTC, capsulated commented on internal/handler/userbalance.go
> +	_context "context"
непривычно видеть нижнее подчёркивание у конекста

2024-08-29 18:38 UTC, capsulated commented on internal/service/accrual/accrual.go
> +var ErrBadRequest = errors.New(http.StatusText(http.StatusBadRequest))
Ну да, тут не должно фигурировать реализации нижнего уровня (http в данном случае)

2024-09-01 07:47 UTC, mikesvis commented on internal/context/user.go
> +const UserIDContextKey ContextKey = "UserID"
Обсудили, пока оставлю так, но главное не увлекаться.

2024-09-01 07:47 UTC, mikesvis commented on internal/app/app.go
> +	db, _ := driversDb.NewPostgres(config)
Понял, сделал

2024-09-01 07:47 UTC, mikesvis commented on internal/app/app.go
> +	config := config.NewConfig()
Готово

2024-09-01 07:51 UTC, mikesvis commented on cmd/gophermart/main.go
> +	app := app.New(&ctx)
Переделал `app -> gophermart`

2024-09-01 07:52 UTC, mikesvis commented on internal/domain/status.go
> +package domain
Обсудили, пока что оставлю бизнес сущности как есть

2024-09-01 07:59 UTC, mikesvis commented on internal/drivers/postgres/postgres.go
> +package drivers
Растащил

2024-09-01 07:59 UTC, mikesvis commented on internal/drivers/queue/queue.go
> +type Queue struct {
Растащил

2024-09-01 08:01 UTC, mikesvis commented on internal/exchange/accrual/accrual.go
> +type OrderAccrualResponse struct {
Исправил

2024-09-01 08:08 UTC, mikesvis commented on internal/exchange/accrual/accrual.go
> +func NewExchange(config *config.Config, logger *zap.SugaredLogger) *Exchange {
Не получается, поскольку config и logger не эспортируемые :( 
`Explicit assignment to unexported fields`
Не хочу только для них делать исключение. Учту на будущее

2024-09-01 08:10 UTC, mikesvis commented on internal/exchange/accrual/accrual.go
> +type Exchange struct {
Да, он взаимодействует с внешним. Хочу такое название ибо `Client` подразумевает только отправку запросов.

2024-09-01 08:14 UTC, mikesvis commented on internal/handler/handler.go
> +type Handler struct {
Вообще замечание корректное, поскольку Handler/Server/Router логически группируются по ответственности. Если можно, то тут пока оставлю так, но учту на будущее.

2024-09-01 08:15 UTC, mikesvis commented on internal/app/app.go
> +	go accrualService.RunQueue(*ctx)
Перенес

2024-09-01 08:15 UTC, mikesvis commented on internal/handler/handler.go
> +func NewHandler(config *config.Config, user *user.Service, order *order.Service, accrual *accrual.Service, logger *zap.SugaredLogger) *Handler {
Учту

2024-09-01 08:18 UTC, mikesvis commented on internal/handler/userbalance.go
> +	// У меня есть вопросы!!! Передайте пожалуста товарщиу кто составлял задание
TODO :)

2024-09-01 08:18 UTC, mikesvis commented on internal/handler/userbalance.go
> +	// Я тогда тоже буду выкручиваться: просто у себя создавать такой заказ (который указан в списании)
Угу

2024-09-01 08:18 UTC, mikesvis commented on internal/handler/userbalance.go
> +	"github.com/mikesvis/gmart/internal/context"
Да, обсудили

2024-09-01 08:19 UTC, mikesvis commented on internal/handler/userbalance.go
> +	_context "context"
Да, обсудили

2024-09-01 08:36 UTC, mikesvis commented on internal/service/accrual/accrual.go
> +var ErrBadRequest = errors.New(http.StatusText(http.StatusBadRequest))
Готово

2024-09-03 20:17 UTC, mikesvis commented on cmd/gophermart/main.go
> +	app.Run()
Не успел, много времени промучался с добавлением тестов на гинкго. В будущем (на боевых проектах) обязательно учту что нужен `graceful shutdown`

2024-09-03 20:19 UTC, mikesvis commented on internal/domain/user.go
Обсудили, учту

2024-09-03 20:20 UTC, mikesvis commented on internal/app/app.go
> +	if err := http.ListenAndServe(string(app.config.RunAddress), app.router); err != nil {
Сделал

2024-09-03 20:26 UTC, mikesvis commented
> Всё в комментах
> 
> Остальное обсудили на 1-1. По доработкам в основном мелочи, немного порядок навести. Всё написано хорошо, читаемо, распределено по пакетам.
> 
> Но кроме мелких замечаний есть только одно серьёзное: нужны тесты, хотя бы на основную логику

Тесты на логику сделал через гинкГо, криво/косо, но это "первый блин" как говорится. Намучился с непривычки. В целом мне понравилось - нужен какой-нибудь мастер класс в рабочем проекте (ну или примеры посмотреть) - в таком виде как у меня это какое-то ламерство, но свою функцию выполняют :)

2024-09-04 00:30 UTC, capsulated commented on cmd/gophermart/main.go
> +	app.Run()
Но тудушку оставить обязательно! )))

2024-09-04 00:38 UTC, capsulated approved these changes
Всё отлично!
Там, где было необходимо - фиксы внесены, там где были какие-то примеры или рекомендации, там ты руководстовался общим стилем программы, это круто 💪

Кроме одного замечания: тесты-то где в итоге? )) Появились баш скрипты запуска автотестов, но собственных ни юнит, ни поведенческих тесов нет.

Апрувлю, но напиши мне в директ, хотелось бы глянуть даже кривой тест на ginkgo, если он в ветку или в каком-то комите не дописанном

2024-09-04 03:55 UTC, merged